name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensures code is checked out

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # Running Maven build on the root `pom.xml`

    - name: Maven Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v1
      with:
        token: ${{ secrets.Token }}

    - name: Record start time
      run: echo "::set-output name=start_time::$(date +%s)"

    - name: Build step
      run: echo "Building project..."

    - name: Record end time and calculate duration
      run: |
        end_time=$(date +%s)
        duration=$((end_time - ${{ steps.start_time.outputs.start_time }}))
        echo "Pipeline took $duration seconds."
